# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-09 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='user',
        ),
    ]
